name: CI

on:
  push:
    branches:
      - "**"  # Bude se spouštět na všech větvích
  pull_request:

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: testdb
                    MYSQL_USER: user
                    MYSQL_PASSWORD: password
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            - name: Set up repository
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.head.sha }}

            - name: Set up Java 21
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: 21

            - name: Wait for MySQL to be ready
              run: sleep 15s

            - name: Make +x for ./gradlew
              working-directory: ./
              run: chmod +x gradlew

            - name: Build and Test (Gradle)
              working-directory: ./
              run: ./gradlew clean --no-build-cache test --info


    frontend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Install BunJS
              run: |
                curl -fsSL https://bun.sh/install | bash
                echo "$HOME/.bun/bin" >> $GITHUB_PATH

            - name: Install dependencies
              working-directory: ./frontend
              run: bun install

            - name: Run tests
              working-directory: ./frontend
              run: bun run test
