name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Java 21
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: 21

            - name: Make +x for ./gradlew
              working-directory: ./backend
              run: chmod +x gradlew

            - name: Build and Test (Gradle)
              working-directory: ./backend
              run: ./gradlew clean test


    frontend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Install BunJS
              run: |
                curl -fsSL https://bun.sh/install | bash
                echo "$HOME/.bun/bin" >> $GITHUB_PATH

            - name: Install dependencies
              working-directory: ./frontend
              run: bun install

            - name: Run tests
              working-directory: ./frontend
              run: bun test

            - name: Build Vue aplikaci
              working-directory: ./frontend
              run: bun run build
